on:
  push:
    tags: ['v*']
  workflow_dispatch: # Manually trigger a release
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'jalil-salame' }}
    environment: "Release to crates.io"
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Authenticate with crates.io
        uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Release with release-plz
        uses: release-plz/action@487eb7b5c085a664d5c5ca05f4159bd9b591182a # v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        with:
          command: release
          registry: crates-io
